trigger: none

pool:
 name: TestPool
 demands:
 - Agent.OS -equals Linux

steps:
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 's203d.azdo.deployment'
