trigger: none

pool:
 name: TestPool
 demands:
 - Agent.OS -equals Linux

steps:
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 's203-eligibilitycheckingservicegovuk-development(244821ce-c33f-48f4-9b47-0157b636c597)'
