trigger: none

pool:
 name: Azure Pipelines

steps:

- task: TerraformTaskV4@4
  name: 'init' 
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 's203d.azdo.deployment'
    backendAzureRmResourceGroupName: 's203d01-tf'
    backendAzureRmStorageAccountName: 's203terraformdev'
    backendAzureRmContainerName: 's203terraform'
    backendAzureRmKey: 'tfstate.state'

- task: TerraformTaskV4@4
  name: 'plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 's203d.azdo.deployment'

- task: TerraformTaskV4@4
  name: 'apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 's203d.azdo.deployment'
