trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Bash Install'
  inputs:
   targetType: inline
   script: |
     yarn set version berry
     yarn set version 2.x
     cd tests
     yarn install

- task: Bash@3
  displayName: 'run cypress tests'
  inputs:
   targetType: inline
   script: |
    cd tests
    yarn e2e:chrome