trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Bash Install'
  inputs:
   targetType: inline
   script: |
     ls
     cd tests
     ls
     npm install

- task: Bash@3
  displayName: 'run cypress tests'
  inputs:
   targetType: inline
   script: |
    cd tests
    export CYPRESS_API_HOST="https://ecs-dev-as.azurewebsites.net"
    export CYPRESS_JWT_USERNAME=$(JWT_USERNAME)
    export CYPRESS_JWT_PASSWORD=$(JWT_PASSWORD)
    npm run e2e:chrome

- task: Bash@3
  condition: always()
  displayName: 'Generate report'
  inputs:
   targetType: inline
   script: |
    cd tests
    ls
    npm run combine:reports

- task: Bash@3
  condition: always()
  displayName: 'Publish test results'
  inputs:
   targetType: inline
   script: |
    ls