//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckYourEligibility.API.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CheckYourEligibility.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DwpClaims_all {
            get {
                return ResourceManager.GetString("DwpClaims_all", resourceCulture);
            }
        }
        
        internal static string DwpClaims_employment_support_allowance_income_based {
            get {
                return ResourceManager.GetString("DwpClaims_employment_support_allowance_income_based", resourceCulture);
            }
        }
        
        internal static string DwpClaims_income_support {
            get {
                return ResourceManager.GetString("DwpClaims_income_support", resourceCulture);
            }
        }
        
        internal static string DwpClaims_job_seekers_allowance_income_based {
            get {
                return ResourceManager.GetString("DwpClaims_job_seekers_allowance_income_based", resourceCulture);
            }
        }
        
        internal static string DwpClaims_pensions_credit {
            get {
                return ResourceManager.GetString("DwpClaims_pensions_credit", resourceCulture);
            }
        }
        
        internal static string DwpClaims_universal_credit {
            get {
                return ResourceManager.GetString("DwpClaims_universal_credit", resourceCulture);
            }
        }
        
        internal static string EcsSoapFsm {
            get {
                return ResourceManager.GetString("EcsSoapFsm", resourceCulture);
            }
        }
    }
}
