//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckYourEligibility.WebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckYourEligibility.WebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;jsonapi&quot;: {
        ///        &quot;version&quot;: &quot;1.0&quot;
        ///    },
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;attributes&quot;: {
        ///                &quot;benefitType&quot;: &quot;carers_allowance&quot;,
        ///                &quot;awards&quot;: [
        ///                    {
        ///                        &quot;amount&quot;: 0,
        ///                        &quot;endDate&quot;: &quot;2029-06-05&quot;,
        ///                        &quot;endReason&quot;: &quot;customer_required_to_be_available_for_work&quot;,
        ///                        &quot;startDate&quot;: &quot;2024-04-08&quot;,
        ///                        &quot;status&quot;: &quot;cacs_decision_hist&quot;
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DwpClaims_all {
            get {
                return ResourceManager.GetString("DwpClaims_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DwpClaims_employment_support_allowance_income_based {
            get {
                return ResourceManager.GetString("DwpClaims_employment_support_allowance_income_based", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///            &quot;attributes&quot;: {
        ///                &quot;benefitType&quot;: &quot;income_support&quot;,
        ///                &quot;awards&quot;: [
        ///                    {
        ///                        &quot;amount&quot;: 1111111,
        ///                        &quot;endDate&quot;: &quot;2029-06-05&quot;,
        ///                        &quot;endReason&quot;: &quot;customer_required_to_be_available_for_work&quot;,
        ///                        &quot;startDate&quot;: &quot;2018-05-06&quot;,
        ///                        &quot;status&quot;: &quot;cacs_decision_hist&quot;
        ///                    }
        ///                ],
        ///                &quot;guid&quot;: &quot;e0f4569cb36590fab2c8cb3a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DwpClaims_income_support {
            get {
                return ResourceManager.GetString("DwpClaims_income_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DwpClaims_job_seekers_allowance_income_based {
            get {
                return ResourceManager.GetString("DwpClaims_job_seekers_allowance_income_based", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;jsonapi&quot;: {
        ///        &quot;version&quot;: &quot;1.0&quot;
        ///    },
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;attributes&quot;: {
        ///                &quot;benefitType&quot;: &quot;pensions_credit&quot;,
        ///                &quot;awards&quot;: [
        ///                    {
        ///                        &quot;amount&quot;: 1111111,
        ///                        &quot;endDate&quot;: &quot;2029-06-05&quot;,
        ///                        &quot;endReason&quot;: &quot;customer_required_to_be_available_for_work&quot;,
        ///                        &quot;startDate&quot;: &quot;2018-05-06&quot;,
        ///                        &quot;status&quot;: &quot;cacs_decision_hist&quot;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DwpClaims_pensions_credit {
            get {
                return ResourceManager.GetString("DwpClaims_pensions_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;jsonapi&quot;: {
        ///        &quot;version&quot;: &quot;1.0&quot;
        ///    },
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;attributes&quot;: {
        ///                &quot;children&quot;: [
        ///                    {
        ///                        &quot;effectiveStartDate&quot;: &quot;2022-03-30&quot;,
        ///                        &quot;fullName&quot;: &quot;ChildTwo Data&quot;,
        ///                        &quot;dateOfBirth&quot;: &quot;2020-01-01&quot;
        ///                    },
        ///                    {
        ///                        &quot;effectiveStartDate&quot;: &quot;2022-03-30&quot;,
        ///                        &quot;fullName&quot;: &quot;ChildOne Data&quot;,
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DwpClaims_universal_credit {
            get {
                return ResourceManager.GetString("DwpClaims_universal_credit", resourceCulture);
            }
        }
    }
}
