// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CheckYourEligibility.AcceptanceTests.Models;

public partial class ApplicationStatuses
{
    public string ApplicationStatusId { get; set; }

    public string ApplicationId { get; set; }

    public string Type { get; set; }

    public DateTime TimeStamp { get; set; }

    public virtual Applications Application { get; set; }
}