// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CheckYourEligibility.AcceptanceTests.Models;

public partial class Audits
{
    public string AuditId { get; set; }

    public string Type { get; set; }

    public string TypeId { get; set; }

    public string Url { get; set; }

    public string Method { get; set; }

    public string Source { get; set; }

    public string Authentication { get; set; }

    public DateTime TimeStamp { get; set; }
}