// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CheckYourEligibility.AcceptanceTests.Models;

public partial class EligibilityCheck
{
    public string EligibilityCheckId { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

    public DateTime Created { get; set; }

    public DateTime Updated { get; set; }

    public string EligibilityCheckHashId { get; set; }

    public string Group { get; set; }

    public int? Sequence { get; set; }

    public string CheckData { get; set; }

    public virtual EligibilityCheckHashes EligibilityCheckHash { get; set; }
}