// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CheckYourEligibility.AcceptanceTests.Models;

public partial class EligibilityCheckHashes
{
    public string EligibilityCheckHashId { get; set; }

    public string Hash { get; set; }

    public string Type { get; set; }

    public DateTime TimeStamp { get; set; }

    public string Outcome { get; set; }

    public string Source { get; set; }

    public virtual ICollection<Applications> Applications { get; set; } = new List<Applications>();

    public virtual ICollection<EligibilityCheck> EligibilityCheck { get; set; } = new List<EligibilityCheck>();
}