// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CheckYourEligibility.AcceptanceTests.Models;

public partial class Establishments
{
    public int EstablishmentId { get; set; }

    public string EstablishmentName { get; set; }

    public string Postcode { get; set; }

    public string Street { get; set; }

    public string Locality { get; set; }

    public string Town { get; set; }

    public string County { get; set; }

    public bool StatusOpen { get; set; }

    public int LocalAuthorityId { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Applications> Applications { get; set; } = new List<Applications>();

    public virtual LocalAuthorities LocalAuthority { get; set; }
}