// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CheckYourEligibility.AcceptanceTests.Models;

public partial class FreeSchoolMealsHmrc
{
    public string FreeSchoolMealsHmrcid { get; set; }

    public int DataType { get; set; }

    public DateTime DateOfBirth { get; set; }

    public string Surname { get; set; }
}