// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CheckYourEligibility.AcceptanceTests.Models;

public partial class FreeSchoolMealsHo
{
    public string FreeSchoolMealsHoid { get; set; }

    public string Nass { get; set; }

    public DateTime DateOfBirth { get; set; }

    public string LastName { get; set; }
}