// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CheckYourEligibility.AcceptanceTests.Models;

public partial class LocalAuthorities
{
    public int LocalAuthorityId { get; set; }

    public string LaName { get; set; }

    public virtual ICollection<Establishments> Establishments { get; set; } = new List<Establishments>();
}