// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CheckYourEligibility.AcceptanceTests.Models;

public partial class Users
{
    public string UserId { get; set; }

    public string Email { get; set; }

    public string Reference { get; set; }

    public virtual ICollection<Applications> Applications { get; set; } = new List<Applications>();
}